# ==========================================
# HOME ASSISTANT AUTOMATIONS - V4.0 SAUBER
# Sämtliche WP-Logik wurde in das "The Rock"
# Package (wp_automationen_v2_KOMPLETT.yaml) ausgelagert!
# ==========================================

- id: weihnachtsbeleuchtung_17_an
  alias: Weihnachtsbeleuchtung 17 Uhr AN
  triggers:
  - at: '17:00:00'
    trigger: time
  conditions: []
  actions:
  - target:
      entity_id: group.weihnachtsbeleuchtung
    action: homeassistant.turn_on
  mode: single

- id: weihnachtsbeleuchtung_22_aus
  alias: Weihnachtsbeleuchtung 22 Uhr AUS
  triggers:
  - at: '22:00:00'
    trigger: time
  conditions: []
  actions:
  - target:
      entity_id: group.weihnachtsbeleuchtung
    action: homeassistant.turn_off
  mode: single
